
//----------------------------------------------------
// The following code was generated by C# CUP v0.1
// 06-03-2014 07:18:42 p.m.
//----------------------------------------------------

namespace TinyMachine.parser
 {

/** CUP generated class containing symbol constants. */
public class TokenDef {
  /* terminals */
  public const int MUL = 7;
  public const int EOF = 0;
  public const int JGE = 15;
  public const int COMENTARIO_LINEA = 24;
  public const int ENTERO = 27;
  public const int JLE = 14;
  public const int JGT = 16;
  public const int FIN_LINEA = 26;
  public const int HALT = 2;
  public const int IN = 3;
  public const int OUT = 4;
  public const int ST = 12;
  public const int ADD = 5;
  public const int SUB = 6;
  public const int PARENT_IZQ = 20;
  public const int COMENTARIO_FIN = 25;
  public const int JEQ = 17;
  public const int error = 1;
  public const int COMA = 22;
  public const int LD = 9;
  public const int ERROR = 23;
  public const int DIV = 8;
  public const int PARENT_DER = 19;
  public const int LDC = 11;
  public const int COLON = 21;
  public const int JNE = 18;
  public const int LDA = 10;
  public const int JLT = 13;
	}
}
